site_name: Learnings

nav:
  - Home: index.md

  - Linux:
      - SSH known_hosts: linux/known_hosts.md

  - Golang:
      - Reconciler basics: golang/reconciler-basics.md

  - Random Stuff:
     - Helpfile: others/Helpfile.md
     - Git Commands: others/gitfilecommands.md
